<article >
	<div class="formulaire">
		<form method="post">
			
		<div>
			<label for="Nom">Nom</label>
			<input type="text" name="name" id="name">
		</div>	

		<div>
			<label for="price_buy">prix d'achat</label>
			<input type="text" name="price_buy" id="price_buy" value="">
		</div>	
		<div>
			<label for="margin_sale">marge</label>
			<input type="text" name="margin_sale" id="margin_sale" value="">
		</div>	
		<!-- <div>
			<label for="price_sell">prix de vente</label>
			<input type="text" name="price_sell" id="price_sell" value="">
		</div>	 -->
		<div>
			<label for="description">déscription</label>
			<input type="text" name="description" id="description" value="">
		</div>	
		<div>
			<label for="stock">stock</label>
			<input type="text" name="stock" id="stock" value="">
		</div>	
		<div>
			<label for="image">image</label>
			<input type="text" name="image" id="image" value="">
		</div>
		<div>
			<label for="id_producer">id_producer</label>
			<input type="text" name="id_producer" id="id_producer" value="">
		</div>
			<!-- <input type="text" name="id_producer" id="name" value=""> -->
		<div>
			
				
			<label for="fruits">Choisir une categorie :</label>
			<br/>
			<input type="text" name="id_category" value="fruit, légume ou viande" id="fruits" checked />
		
		</div>
		<div>
			<button type="submit" name="create" value="create">send</button>
		</div>
		</form>
	</div>
</article>