 
<article >
	<div class="formulaire">
		<form method="post">
			
		<div>
			<label for="Nom">Nom</label>
			<input type="text" name="name" id="name">
		</div>	
		<div>
			<label for="price_buy">prix d'achat</label>
			<input type="text" name="price_buy" id="price_buy" value="">
		</div>	
		<div>
			<label for="margin_sale">marge</label>
			<input type="text" name="margin_sale" id="margin_sale" value="">
		</div>	
		<div>
			<label for="description">déscription</label>
			<input type="text" name="description" id="description" value="">
		</div>			
		<div>
			<label for="image">image</label>
			<input type="text" name="image" id="image" value="">
		</div>

		<div>				
			<label for="id_category">Choisir une categorie :</label>
			<br/>			
			<select name="category" class="form-control">
				  	<?php require 'controller/selectcat.php'; ?>
			</select>
		
		</div>
		<div>
			<button type="submit" name="create" value="create">send</button>
		</div>
		</form>
	</div>

	<div class="formulaire">
	<!--	<?=$error?>  -->
		<form method="post" action="index.php?page=category">
			<!-- login -->
			<div>
				<label for="creacat">Créer une catégorie :</label>
				<input id="creacat" type="text" name="creacat" placeholder=""/>
			</div>
			<!-- Connexion -->
			<div>
				<button type="submit" name="create" value="create">Validé</button>
			</div>
		</form>
	</div>

</article>