<!--	
<link href='https://fonts.googleapis.com/css?family=Courgette|Open+Sans' rel='stylesheet' type='text/css'>

<link type="text/css" rel="stylesheet" href="../public/styles/style.css"/>
-->

<div class="blocHome fontStyle">
<!-- <form method="post" class="noMarginBottom"> -->
	<div class="imageHome">
		<a href="index.php?page=product&id=<?=$product->getIdProduct()?>">
			<img src="<?=htmlentities($product->getImage())?>" class="textCenter">
		</a>
	</div>
	<div class="textCenter clearfix">
		<h2 class="prixHome">
			<?=htmlentities($product->getPriceSell())?>
		</h2>

		<h2 class="devisePoids">eur./Kg</h2>
	</div>
	<div>
		<h4 class="nameHome">
			<?=htmlentities($product->getName())?></a>
		</h4>

		<h6 class="descripHome">	
			<?=htmlentities($product->getDescription())?>
		</h6>
	</div>
	<div>
		<!-- Ajout au panier -->
		<input type="hidden" name="page" value="caddy">
        <input type="hidden" value="<?=$product->getIdProduct();?>" name="id" class="ajoutPanier"/>
        <a type="submit" href="index.php?page=product&id=<?=$product->getIdProduct()?>"><button>ajouter</button>
		</a>
		<!-- </form> -->
	</div>
</div>
