<div style="width:100%">
  	<p style="color:#FFF;
  				font-family: 'Courgette', cursive;
			  	font-size:2.5em;
			  	text-align:center;
			  	border-radius:35px;
			  	width:60%;
			  	background-color:#D00;
			  	padding:10px;
			  	margin:0 auto;
			  	margin-top:10px;
			  	margin-bottom:10px;
			  	border:4px black solid;
			  	box-shadow:inset 0px 4px 0.3em #7C0000;">
  		
  		<strong style="color:#000">Erreur : </strong><?=$error?>
  	</p>
</div>