	<header class="menuDesign fontStyle">
		<h1>La boutique</h1>
		<nav class="menu">
			<ul>
				<li>
					<a class="nav" href="#">Accueil</a>
				</li>
				<li>
					<a class="nav" href="#">Produits</a>
				</li>
				<li class="sous-menu">
					<a class="nav" href="#">Mon Compte</a>
					<ul>
						<li><a class="nav" href="#">Historique des commandes</a></li>
						<li><a class="nav" href="#">Donner mon avis</a></li>
						<li><a class="nav" href="index.php?page=logout">Deconnexion</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</header>