<header class="menuDesign fontStyle">
		<form>
			<input type="hidden" name="page" value="recherche">
            <div>
                <input type="text" id="in_recherche" name="recherche" placeholder="Tapez votre recherche" onfocus="this.value = this.value;" class="windowRecherche" value="<?=$search?>" autofocus>
            </div>
		</form>
		<div class="fontStyle fontColor windowCaddy">
			<p class="pNoMargin">Champ d'affichage d'informations</p>
				<a href="index.php?page=panier">
				</a>
		</div>
	<h1>La boutique</h1>
		<nav class="menu">
			<ul>
				<li>
					<a class="nav" href="index.php?page=home">Accueil</a>
				</li>
				<li class="sous-menu">
					<a class="nav" href="#">Produits</a>
					<ul>
						<?php require 'controller/select_cat_menu.php' ?>
					</ul>
				</li>
				<li class="sous-menu">
					<a class="nav" href="#">Mon Compte - <?=$_SESSION['user']?></a>
					<ul>
						<li><a class="nav" href="index.php?page=logout">Deconnexion</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</header>