<header class="menuDesign fontStyle">
		<form>
			<input type="hidden" name="page" value="recherche">
            <div>
                <input type="text" name="recherche" placeholder="Tapez votre recherche" class="windowRecherche">
            </div>
		</form>

		<div class="fontStyle fontColor windowCaddy">
			<p class="pNoMargin">Mon caddy</p>
			<a href="index.php?page=panier"></a>
		</div>

	<h1>La boutique</h1>
	<nav class="menu">
		<ul>
			<li>
				<a class="nav" href="index.php?page=home">Accueil</a>
			</li>
			<li class="sous-menu">
				<a class="nav" href="index.php?page=category">Produits </a>
				<ul>
					<?php require 'controller/select_cat_menu.php' ?>
				</ul>
			</li>				
			<li class="sous-menu">
				<a class="nav" href="#">Se Connecter </a>
				<ul>
					<li><a class="nav" href="index.php?page=login_register_user">Particulier</a></li>
					<li><a class="nav" href="index.php?page=login_register_pro">Professionnel</a></li>
					<li><a class="nav" href="index.php?page=login_admin">Administrateur</a></li>
				</ul>
			</li>
		</ul>
	</nav>
</header>