	<header class="menuDesign fontStyle">
		<h1>La boutique 2</h1>
		<nav class="menu">
			<ul>
				<li>
					<a class="nav" href="index.php?page=home">Accueil</a>
				</li>
				<li>
					<a class="nav" href="index.php?page=product">Produits</a>
				</li>
				<li>
					<a class="nav" href="index.php?page=product">Fruits</a>
				</li>
				<li>
					<a class="nav" href="index.php?page=product">Legumes</a>
				</li>
				<li>
					<a class="nav" href="index.php?page=product">Viandes</a>
				</li>
				<li class="sous-menu">
					<a class="nav" href="#">Mon Compte - <?=$_SESSION['producer']?></a>
					<ul>
						<li><a class="nav" href="index.php?page=logout">Deconnexion</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</header>