
<article>
	<div class="clearfix:after">		
		<div class="block1 fontStyle fontColor">
				<h2>Notre démarche:</h2>
				L'id&eacute;e de cr&eacute;er un site de vente en ligne de produits bio nous est venue suite &agrave; la demande de notre très v&eacute;n&eacute;r&eacute; Gourou Pascal. Le but &eacute;tait de proposer &agrave; la consommation non pas des "Chocapic" mais de la viande qui envoie du "Steack" comme dirait notre mentor ... d'accord? ... et le rendre accessible d&egrave;s le d&eacute;but au plus grand nombre &agrave; savoir 9 personnes ... alors comme dirait notre guide supr&ecirc;me "et voil&agrave;&agrave;&agrave;aa!" ...  C'est tout! ...	
		</div>
		<div class="block2 fontStyle fontColor">
				<h2>Vos garanties:</h2>
				Nous utilisons beaucoup de produits recycl&eacute;s, papier, cartons mais pas de denr&eacute;es alimentaires recycl&eacute;es ... enfin en principe.
			</p>
		</div>
	</div>
</article>
<?php require('controller/bloc_home_category.php'); ?>
<?php require('controller/bloc_home_opinion.php'); ?>
