<article>		
	<div class="block1">
		<p>
			<h2>Lorem ipsum</h2>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
		</p>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
		</p>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
		</p>
	
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
		</p>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
		</p>
	
	
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
		</p>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
		</p>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum su
		<p>
	</div>
	<div class="block2">
			<h2>Lorem ipsum</h2>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
		</p>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
		</p>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum.
		</p>
	</div>

</article>	
	

	<?php
		require('controller/bloc_home_opinion.php');
		require('controller/bloc_home_category.php');
	?>
</article>		

