
<article>
	<div class="clearfix:after">		
		<div class="block1 fontStyle fontColor">
				<h2>Lorem ipsum</h2>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
				<br>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit.		
		</div>
		<div class="block2 fontStyle fontColor">
				<h2>Lorem ipsum</h2>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolor obcaecati, quisquam at ipsum odit excepturi error reiciendis iste, vitae velit est amet nulla voluptatibus rerum, fugiat cum suscipit iusto.
			</p>
		</div>
	</div>
</article>
<?php require('controller/bloc_home_category.php'); ?>
<?php require('controller/bloc_home_opinion.php'); ?>
