<article>
	
	<div class="formulaire menuDesign daltoFontStyle">
		<h2>Je suis un particulier :</h2>
		<form method="post">	
	    	<!-- nom -->
	    	<div>
	    		<label for="aliasnom">Nom :</label>
	    		<input id="aliasnom" type="text" name="name" placeholder="Votre NOM"/>
			</div>
			<!-- prenom -->
			<div>
	    		<label for="aliasprenom">Prénom :</label>
	    		<input id="aliasprenom" type="text" name="firstname" placeholder="Votre PRENOM"/>
			</div>
			<!-- e-mail -->
			<div>
				<label for="aliasemail">Adresse e-mail :</label>
				<input id="aliasemail" type="email" name="mail" placeholder="Votre EMAIL"/>
			</div>
			<!-- password -->
			<div>
				<label for="aliasmdp">Mot de passe :</label>
			    <input id="aliasmdp" type="password" name="password"/>
		    </div>
		    <div>
		    	<label for="aliascmdp">Confirm. mot de passe :</label>
			    <input id="aliascmdp" type="password" name="password2"/>
			</div>
			<!-- adresse -->
			<p class="marginVertical">Adresse de facturation :</p>
			<div>
	    		<label for="aliasadresse">Adresse :</label>
	    		<input id="aliasadresse" type="text" name="address" placeholder="Rue, Ville et Code postal :"/>
			</div>
			<!-- telephone -->
			<div>
		    	<label for="aliastel">Téléphone :</label>
		    	<input id="aliastel" type="text" name="phone" placeholder="+33"/>
			</div>
			
			<!-- valid -->
			<div>
				<button type="submit" name="register" value="register" class="submitButton">Envoyer</button>
			</div>
		</form>
	</div>

	<div class="formulaire menuDesign fontStyle">
	<!--	<?=$error?>  -->
		<h2>Connexion:</h2>
		<form method="post">
			<!-- login -->
			<div>
				<label for="aliaslogin">Nom :</label>
				<input id="aliaslogin" type="text" name="name" placeholder=""/>
			</div>
			<!-- password -->
			<div>
				<label for="aliasmdp">Mot de passe :</label>
			    <input id="aliasmdp" type="password" name="password"/>
			</div>
			<!-- Connexion -->
			<div>
				<button type="submit" name="login" value="login" class="submitButton">Connexion</button>
			</div>
		</form>
	</div>

</article>