<div class="panier">
	<h2 class="h2">Votre "Panier" :</h2>
	<?php require('controller/listpanier.php'); ?>

	<div class="facture">
		<h2>Récapitulatif :</h2>
		<p>Nombre de produits : <?=sizeof($caddy->getProducts())?></p>
		<p>Poids global : <?=$caddy->getWeight()?> kg</p>
		<p>Prix T.T.C. : <?=$caddy->getFullPrice()?> €</p>
		<p>Adresse de facturation : <?=$user->getAddress()?></p>
		<p>Téléphone de contact : <?=$user->getPhone()?></p>
		<div>
			<button type="submit" name="paiment" value="paiment" class="submitButton button">Payer votre commande</button>
		</div>
	</div>
</div>