 
<article >
	<div class="formulaire">
		<form method="post">
			
		<div>
			<select>
				<optgroup label="<?=htmlentities($category->getTitle())?>" name="category" value="<?=htmlentities($category->getIdCategory())?>" class="form-control">
						  	<option value="<?=htmlentities($product->getIdProduct())?>"><?=htmlentities($product->getName())?></option>
				</optgroup>
	</select>
		</div>	
		<div>
			<input type="text" name="quantity_delivery">
		</div>
		
	
				<button type="submit" name="selectprod" value="selectprod">Validé</button>
			</div>
		</form>
	</div>

</article>