<!--
<link href='https://fonts.googleapis.com/css?family=Courgette|Open+Sans' rel='stylesheet' type='text/css'>

<link type="text/css" rel="stylesheet" href="../public/styles/style.css"/>
-->
<div class="blocCaddy fontStyle">
	<div class="divImageCaddy">
		<a href="index.php?page=product&id=<?=$product->getIdProduct()?>">
		<img src="<?=htmlentities($product->getImage())?>">
		</a>
	</div>
	<div>
		<h2 class="prixCaddy">
			<?=htmlentities($product->getPriceSell())?>
		</h2>

		<h2 class="devisePoidsCaddy">eur./Kg</h2>
		
		<h4 class="nameCaddy">
			<?=htmlentities($product->getName())?>
		</h4>
		
		<h6 class="descriptCaddy floatRight">
			<?=htmlentities($product->getDescription())?>
		</h6>
		<!-- Quantité et suppression -->
		<form class="formCaddy" method="POST" action="index.php?page=caddy">
			<h4 class="indicCaddy">veuillez indiquez votre quantite</h4>
			<input type="hidden" name="id_product" value="<?=$product->getIdProduct()?>">
            <input type="text" class="inputCaddy quantCaddy" name="quantity" placeholder="Uniquement par 0.5kg SVP !"/>
            <input type="submit" value="valider" name="add_caddy" class="suppCaddy"/>
		</form>

	</div>
</div>


