<!--
<link href='https://fonts.googleapis.com/css?family=Courgette|Open+Sans' rel='stylesheet' type='text/css'>

<link type="text/css" rel="stylesheet" href="../public/styles/style.css"/>
-->
<div class="blocCaddy fontStyle">
	<div>
		<!--<a href="#" class="imageCaddy">-->
		<img src="./public/images/peches.jpg" class="imageCaddy">
		<?=htmlentities($product['image'])?>
		</a>
	</div>
	<div>
		<h2 class="prixCaddy">
			<?=htmlentities($product->getPriceSell())?>
		</h2>

		<h2 class="devisePoidsCaddy">eur./Kg</h2>

		<h4 class="nameCaddy">
		<?=htmlentities($product->getName())?>
		</h4>

		<h6 class="descriptCaddy floatRight">
			<?=htmlentities($product->getDescription())?>
		</h6>
		<!-- Ajout au panier -->
		<form class="formCaddy">
 	        <input type="submit" value="Rajouter a mon panier" class="ajoutPanier largeBouton"/>
		</form>

	</div>
</div>

<!--
<?php require('controller/traitement_caddy.php'); ?>
-->