<article >
	<div class="formulaire">
		<form method="post">	
			<div>
				<label for="name_product">Nom du produit :</label>
				<input id="name_product" type="text" name="name_product" placeholder="Nom du produit"/>
			</div>
			<div>
				<label for="price_buy">Prix d'achat :</label>
				<input id="price_buy" type="text" name="price_buy" placeholder="Prix d'achat :"/>
			</div>
			<div>
				<label for="margin_sale">Marge :</label>
				<input id="margin_sale" type="text" name="margin_sale" placeholder="Marge :"/>
			</div>
			<div>
				<label for="price_sell">Prix de vente :</label>
				<input id="price_sell" type="text" name="price_sell" placeholder="Prix de vente :"/>
			</div>
			<div>
				<label for="description">Description produit :</label>
				<input id="description" type="text" name="description" placeholder="Description produit :"/>
			</div>
			<div>
				<label for="stock">Stock :</label>
				<input id="stock" type="text" name="stock" placeholder="stock"/>
			</div>
		</form>
	</div>
</article>