<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>Boutique Bio</title>
		<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
		<link href='https://fonts.googleapis.com/css?family=Courgette|Open+Sans' rel='stylesheet' type='text/css'>

		<link type="text/css" rel="stylesheet" href="public/styles/style.css"/>
	</head>
	<body>
		<main class="contenair">
		<?php
			require('controller/header.php');
			require('controller/content.php');
			require('controller/footer.php');
		?>
		</main>
		<script>
		$('#in_recherche').keyup(function()
		{
			var search = $(this).val();
			if (search == '')
				return;
			if ($('#list_recherche').length > 0)
			{
				$('#list_recherche').load('index.php?page=recherche&ajax&recherche='+search);
			}
			else
				$('#in_recherche').parents('form').submit();
		});
		</script>
	</body>
</html>