<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>Boutique Bio</title>
		<link type="text/css" rel="stylesheet" href="public/styles/style.css"/>
	</head>
	<body>
		<main class="contenair">
		<?php
			require('controller/header.php');
			require('controller/content.php');
			require('controller/footer.php');
		?>
		</main>
	</body>
</html>